Repository JNU-Parking-Ticket-Project/Parking-Ticket-FE, pull requests merged in 2024-10, with the labels that each got.

#242 refactor: 차량 번호 input에 공백 문자 입력 제한
  service-apply/src/components/apply/ApplyForm.tsx
  service-apply/src/functions/replacer.ts
  service-apply/src/hooks/apply/useApplyFormContext.tsx
Labels: 기능변경

#243 fix: response가 ok가 아닌 경우 error response를 반환한다.
  service-apply/src/functions/https.ts
  service-manager/src/components/announcement/AnnouncementCreate.tsx
  service-manager/src/components/announcement/AnnouncementUpdate.tsx
  service-manager/src/components/notice/NoticeUpdate.tsx
  service-manager/src/functions/https.ts
Labels: 버그

#248 refactor: 중복 파일 제거
  service-manager/src/hooks/react-query/useNoticeForm.tsx
  service-manager/src/hooks/useNoticeForm.tsx
Labels: 성능개선, 중복
